#!/usr/bin/env python3
"""PooleShield v5.3.0 portable Windows build helper.

Defensive purpose:
  Generate and optionally execute a local PyInstaller build plan for the
  PooleShield desktop app. This helper never scans user files, deletes files,
  quarantines files, installs drivers, or uploads data. It only inspects the
  source tree and writes build artifacts when explicitly requested.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

VERSION = "5.3.0"
DEFAULT_APP_NAME = "PooleShield"
DEFAULT_ENTRY = "pooleshield_portable_launcher.py"
DEFAULT_SPEC_PATH = "build/pooleshield_portable.spec"
DEFAULT_DIST_DIR = "dist"
DEFAULT_WORK_DIR = "build/pyinstaller"

DATA_PATHS = [
    "examples/rule_packs/file_av_rules.default.json",
    "policy_config.default.json",
    "policy_config.balanced.json",
    "policy_config.strict.json",
    "README.md",
    "NOTICE.md",
    "LICENSE",
    "DESKTOP_UI_GUIDE.md",
    "ENGINE_API_GUIDE.md",
    "PRIVACY_BUNDLE_GUIDE.md",
]

HIDDEN_IMPORTS = [
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "sqlite3",
]


def root_path(root: Optional[str] = None) -> Path:
    return Path(root or Path.cwd()).resolve()


def pyinstaller_executable() -> Optional[str]:
    """Return a visible PyInstaller console command, if PATH exposes one."""
    return shutil.which("pyinstaller") or shutil.which("pyinstaller.exe")


def pyinstaller_module_available() -> bool:
    """Return whether the current Python can run `python -m PyInstaller`."""
    try:
        return importlib.util.find_spec("PyInstaller.__main__") is not None or importlib.util.find_spec("PyInstaller") is not None
    except (ImportError, ModuleNotFoundError, AttributeError, ValueError):
        return False


def pyinstaller_available() -> bool:
    return pyinstaller_executable() is not None or pyinstaller_module_available()


def pyside6_available() -> bool:
    try:
        import PySide6  # type: ignore # noqa: F401
        return True
    except Exception:
        return False


def build_status(root: Optional[str] = None) -> Dict[str, Any]:
    repo = root_path(root)
    entry = repo / DEFAULT_ENTRY
    required = [repo / p for p in DATA_PATHS] + [entry, repo / "pooleshield_desktop.py", repo / "pooleshield_operator.py"]
    missing = [str(p.relative_to(repo)) for p in required if not p.exists()]
    return {
        "tool": "PooleShield portable Windows build helper",
        "version": VERSION,
        "mode": "portable-build-status",
        "root": str(repo),
        "platform": platform.platform(),
        "python": sys.version.split()[0],
        "windows": platform.system().lower() == "windows",
        "pyinstaller_available": pyinstaller_available(),
        "pyinstaller_executable": pyinstaller_executable() or "",
        "pyinstaller_module_available": pyinstaller_module_available(),
        "pyside6_available": pyside6_available(),
        "entry_exists": entry.exists(),
        "missing_required_files": missing,
        "safe_to_attempt_build": not missing,
        "build_artifacts_gitignored": True,
        "safety_boundary": {
            "build_only": True,
            "scanned_files_opened": False,
            "scanned_files_executed": False,
            "files_deleted": False,
            "files_quarantined": False,
            "drivers_or_hooks_installed": False,
            "network_uploads": False,
        },
    }


def _datas_for_spec(repo: Path) -> List[Tuple[str, str]]:
    pairs: List[Tuple[str, str]] = []
    for rel in DATA_PATHS:
        src = repo / rel
        if src.exists():
            parent = Path(rel).parent
            dest = "." if str(parent) == "." else str(parent)
            pairs.append((str(src), dest))
    return pairs


def render_spec(
    *,
    root: Optional[str] = None,
    app_name: str = DEFAULT_APP_NAME,
    entry: str = DEFAULT_ENTRY,
    dist_dir: str = DEFAULT_DIST_DIR,
    work_dir: str = DEFAULT_WORK_DIR,
    windowed: bool = True,
) -> str:
    repo = root_path(root)
    entry_path = repo / entry
    datas_repr = repr(_datas_for_spec(repo))
    hidden_repr = repr(HIDDEN_IMPORTS)
    console = "False" if windowed else "True"
    return f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by PooleShield portable_build.py v{VERSION}.
# This spec builds a portable local desktop app. It does not include local
# baselines, configs, scan history DBs, result bundles, or private outputs.

block_cipher = None


a = Analysis(
    [{str(entry_path)!r}],
    pathex=[{str(repo)!r}],
    binaries=[],
    datas={datas_repr},
    hiddenimports={hidden_repr},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={app_name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console={console},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name={app_name!r},
)
"""


def write_spec(
    spec_path: str = DEFAULT_SPEC_PATH,
    *,
    root: Optional[str] = None,
    app_name: str = DEFAULT_APP_NAME,
    entry: str = DEFAULT_ENTRY,
    dist_dir: str = DEFAULT_DIST_DIR,
    work_dir: str = DEFAULT_WORK_DIR,
    windowed: bool = True,
    force: bool = False,
) -> Dict[str, Any]:
    repo = root_path(root)
    spec = repo / spec_path
    if spec.exists() and not force:
        raise FileExistsError(f"spec already exists: {spec}. Use --force to overwrite.")
    text = render_spec(root=str(repo), app_name=app_name, entry=entry, dist_dir=dist_dir, work_dir=work_dir, windowed=windowed)
    spec.parent.mkdir(parents=True, exist_ok=True)
    spec.write_text(text, encoding="utf-8")
    return {
        "tool": "PooleShield portable Windows build helper",
        "version": VERSION,
        "mode": "portable-build-write-spec",
        "root": str(repo),
        "spec_path": str(spec),
        "app_name": app_name,
        "entry": entry,
        "dist_dir": str(repo / dist_dir),
        "work_dir": str(repo / work_dir),
        "windowed": windowed,
        "safety_boundary": build_status(str(repo))["safety_boundary"],
    }


def build_command(
    spec_path: str = DEFAULT_SPEC_PATH,
    *,
    root: Optional[str] = None,
    clean: bool = False,
    noconfirm: bool = True,
) -> List[str]:
    repo = root_path(root)
    executable = pyinstaller_executable()
    if executable:
        cmd = [executable]
    else:
        cmd = [sys.executable, "-m", "PyInstaller"]
    if clean:
        cmd.append("--clean")
    if noconfirm:
        cmd.append("--noconfirm")
    cmd.append(str(repo / spec_path))
    return cmd


def build_plan(
    *,
    root: Optional[str] = None,
    spec_path: str = DEFAULT_SPEC_PATH,
    app_name: str = DEFAULT_APP_NAME,
    entry: str = DEFAULT_ENTRY,
    dist_dir: str = DEFAULT_DIST_DIR,
    work_dir: str = DEFAULT_WORK_DIR,
    windowed: bool = True,
    clean: bool = False,
) -> Dict[str, Any]:
    repo = root_path(root)
    status = build_status(str(repo))
    return {
        "tool": "PooleShield portable Windows build helper",
        "version": VERSION,
        "mode": "portable-build-plan",
        "root": str(repo),
        "status": status,
        "spec_path": str(repo / spec_path),
        "app_name": app_name,
        "entry": entry,
        "dist_dir": str(repo / dist_dir),
        "work_dir": str(repo / work_dir),
        "windowed": windowed,
        "command": build_command(spec_path, root=str(repo), clean=clean),
        "expected_portable_folder": str(repo / dist_dir / app_name),
        "expected_launcher": str(repo / dist_dir / app_name / f"{app_name}.exe"),
        "notes": [
            "Run on Windows for the actual portable .exe build.",
            "Generated dist/build folders are local artifacts and must not be committed.",
            "The portable app keeps local config, baselines, history, and scan outputs under operator-controlled local paths.",
        ],
    }


def run_pyinstaller(spec_path: str = DEFAULT_SPEC_PATH, *, root: Optional[str] = None, clean: bool = False) -> Dict[str, Any]:
    repo = root_path(root)
    if not pyinstaller_available():
        raise RuntimeError("PyInstaller is not installed. Run: python -m pip install -r requirements-build.txt")
    cmd = build_command(spec_path, root=str(repo), clean=clean)
    proc = subprocess.run(cmd, cwd=repo, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return {
        "tool": "PooleShield portable Windows build helper",
        "version": VERSION,
        "mode": "portable-build-run",
        "root": str(repo),
        "command": cmd,
        "returncode": proc.returncode,
        "stdout_tail": proc.stdout[-4000:],
        "stderr_tail": proc.stderr[-4000:],
        "success": proc.returncode == 0,
    }


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Build/status helper for PooleShield v5.3.0 portable Windows app.")
    parser.add_argument("--root", default=".")
    parser.add_argument("--status", action="store_true")
    parser.add_argument("--write-spec", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--run-pyinstaller", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--name", default=DEFAULT_APP_NAME)
    parser.add_argument("--entry", default=DEFAULT_ENTRY)
    parser.add_argument("--spec-path", default=DEFAULT_SPEC_PATH)
    parser.add_argument("--dist-dir", default=DEFAULT_DIST_DIR)
    parser.add_argument("--work-dir", default=DEFAULT_WORK_DIR)
    parser.add_argument("--console", action="store_true", help="Build a console app instead of a windowed app")
    parser.add_argument("--output", default=None, help="Optional JSON output path")
    args = parser.parse_args(argv)

    try:
        if args.status:
            result = build_status(args.root)
        elif args.write_spec:
            result = write_spec(args.spec_path, root=args.root, app_name=args.name, entry=args.entry, dist_dir=args.dist_dir, work_dir=args.work_dir, windowed=not args.console, force=args.force)
        elif args.run_pyinstaller:
            if not Path(args.root, args.spec_path).exists():
                write_spec(args.spec_path, root=args.root, app_name=args.name, entry=args.entry, dist_dir=args.dist_dir, work_dir=args.work_dir, windowed=not args.console, force=True)
            result = run_pyinstaller(args.spec_path, root=args.root, clean=args.clean)
        else:
            result = build_plan(root=args.root, spec_path=args.spec_path, app_name=args.name, entry=args.entry, dist_dir=args.dist_dir, work_dir=args.work_dir, windowed=not args.console, clean=args.clean)
    except Exception as exc:
        result = {"ok": False, "version": VERSION, "error_type": exc.__class__.__name__, "error": str(exc)}
        if args.output:
            Path(args.output).write_text(json.dumps(result, indent=2), encoding="utf-8")
        print(json.dumps(result, indent=2))
        return 2

    result.setdefault("ok", True)
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if result.get("ok") else 2


if __name__ == "__main__":
    raise SystemExit(main())
